In [18]:
import pandas as pd
aireDatos = pd.read_csv("../csv/qualitat_aire_dades.csvcsv", sep=";")
aireDatos.head()

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H12,V12
0,8,Barcelona,19,Barcelona,4,7,2024,3,1,5.0,V
1,8,Barcelona,19,Barcelona,4,7,2024,3,2,6.0,V
2,8,Barcelona,19,Barcelona,4,7,2024,3,3,3.0,V
3,8,Barcelona,19,Barcelona,4,7,2024,3,4,5.0,V
4,8,Barcelona,19,Barcelona,4,7,2024,3,5,5.0,V

In [20]:
aireContaminada = pd.read_csv("../csv/qualitat_aire_contaminants.csv", sep=",")
aireContaminada.head()

   Codi_Contaminant Desc_Contaminant Unitats
0                 1              SO2   µg/m³
1                 6               CO   mg/m³
2                 7               NO   µg/m³
3                 8              NO2   µg/m³
4                 9            PM2.5   µg/m³

In [22]:
aireEstacion = pd.read_csv("../csv/qualitat_aire_estacions.csv", sep=",")
aireEstacion.head()

,Estacio,nom_cabina,codi_dtes,zqa,codi_eoi,Longitud,Latitud,ubicacio,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Clas_1,Clas_2,Codi_Contaminant
0,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,8
1,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,10
2,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,7
3,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,12
4,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,8